TARGET := iphone:clang:latest:14.0


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = rbxupgradespoof

rbxupgradespoof_FILES = Tweak.x
rbxupgradespoof_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
